name: istheeconomygood
services:
  - name: economy
    # envs:
    # - key: SOME_SECRET
    #   value: ${SOME_SECRET_FROM_REPOSITORY}
    #   type: SECRET
    github:
      branch: main
      repo: bklosk/istheeconomygood
