name: Deploy site to digitalocean

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            economy
            .do/app.yaml
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        # env:
        #   SOME_SECRET_FROM_REPOSITORY: ${{ secrets.SOME_SECRET_FROM_REPOSITORY }}
        with:
          token: ${{ secrets.DO_TOKEN }}
